[project]
name = "seismic-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Raphael Ramos", email = "raphaelramos@geowellex.com" }
]
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
]

[project.scripts]
seismic-processing = "seismic_processing:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
